// Generated by //hardware/ip/chi_noc/nocgen from irregular.yml. Do not edit.
//
// 3x2 with an empty crosspoint and a doubly-populated one
//
// A 3x2 mesh of crosspoints. Each carries CHI's four channel
// classes as four independent switches sharing nothing, which is what makes the
// protocol deadlock-free here; see //hardware/ip/chi_noc/README.md.
//
// A port is one `chi_xp_port_t` each way -- the four channels' flits, plus the
// L-Credits for the four it receives -- so wiring a neighbour is one assignment
// rather than thirty.
module irregular_noc
  import chi_noc_pkg::chi_xp_port_t;
  import chi_noc_pkg::CHI_XP_EAST;
  import chi_noc_pkg::CHI_XP_WEST;
  import chi_noc_pkg::CHI_XP_NORTH;
  import chi_noc_pkg::CHI_XP_SOUTH;
  import chi_noc_pkg::CHI_XP_P0;
  import chi_noc_pkg::CHI_XP_P1;
(
  input  logic clk_i,
  input  logic rst_ni,

  // rnf0: RN-F at (0, 0) P0, NodeID 11'h000
  input  chi_xp_port_t rnf0_rx_i,
  output chi_xp_port_t rnf0_tx_o,
  // rnf1: RN-F at (0, 0) P1, NodeID 11'h001
  input  chi_xp_port_t rnf1_rx_i,
  output chi_xp_port_t rnf1_tx_o,
  // hnf0: HN-F at (2, 0) P0, NodeID 11'h100
  input  chi_xp_port_t hnf0_rx_i,
  output chi_xp_port_t hnf0_tx_o,
  // hnf1: HN-F at (2, 1) P0, NodeID 11'h108
  input  chi_xp_port_t hnf1_rx_i,
  output chi_xp_port_t hnf1_tx_o,
  // snf0: SN-F at (0, 1) P0, NodeID 11'h008
  input  chi_xp_port_t snf0_rx_i,
  output chi_xp_port_t snf0_tx_o
);

  // Indexed [y][x][direction]. `rx` is what a crosspoint is given, `tx` what it
  // drives, so a link is one assignment of the second to the first.
  chi_xp_port_t [1:0][2:0][5:0] xp_rx;
  chi_xp_port_t [1:0][2:0][5:0] xp_tx;

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // Links
  ////////////////////////////////////////////////////////////////////////////////////////////////

  assign xp_rx[0][0][CHI_XP_EAST] = xp_tx[0][1][CHI_XP_WEST];
  assign xp_rx[0][0][CHI_XP_NORTH] = xp_tx[1][0][CHI_XP_SOUTH];
  assign xp_rx[0][1][CHI_XP_EAST] = xp_tx[0][2][CHI_XP_WEST];
  assign xp_rx[0][1][CHI_XP_WEST] = xp_tx[0][0][CHI_XP_EAST];
  assign xp_rx[0][1][CHI_XP_NORTH] = xp_tx[1][1][CHI_XP_SOUTH];
  assign xp_rx[0][2][CHI_XP_WEST] = xp_tx[0][1][CHI_XP_EAST];
  assign xp_rx[0][2][CHI_XP_NORTH] = xp_tx[1][2][CHI_XP_SOUTH];
  assign xp_rx[1][0][CHI_XP_EAST] = xp_tx[1][1][CHI_XP_WEST];
  assign xp_rx[1][0][CHI_XP_SOUTH] = xp_tx[0][0][CHI_XP_NORTH];
  assign xp_rx[1][1][CHI_XP_EAST] = xp_tx[1][2][CHI_XP_WEST];
  assign xp_rx[1][1][CHI_XP_WEST] = xp_tx[1][0][CHI_XP_EAST];
  assign xp_rx[1][1][CHI_XP_SOUTH] = xp_tx[0][1][CHI_XP_NORTH];
  assign xp_rx[1][2][CHI_XP_WEST] = xp_tx[1][1][CHI_XP_EAST];
  assign xp_rx[1][2][CHI_XP_SOUTH] = xp_tx[0][2][CHI_XP_NORTH];

  // Ports that go nowhere. PortEnable removes their logic, so nothing reads
  // these; driving them keeps the elaborated netlist free of undriven nets
  // without adding any.
  assign xp_rx[0][0][CHI_XP_WEST] = '0;
  assign xp_rx[0][0][CHI_XP_SOUTH] = '0;
  assign xp_rx[0][1][CHI_XP_SOUTH] = '0;
  assign xp_rx[0][1][CHI_XP_P0] = '0;
  assign xp_rx[0][1][CHI_XP_P1] = '0;
  assign xp_rx[0][2][CHI_XP_EAST] = '0;
  assign xp_rx[0][2][CHI_XP_SOUTH] = '0;
  assign xp_rx[0][2][CHI_XP_P1] = '0;
  assign xp_rx[1][0][CHI_XP_WEST] = '0;
  assign xp_rx[1][0][CHI_XP_NORTH] = '0;
  assign xp_rx[1][0][CHI_XP_P1] = '0;
  assign xp_rx[1][1][CHI_XP_NORTH] = '0;
  assign xp_rx[1][1][CHI_XP_P0] = '0;
  assign xp_rx[1][1][CHI_XP_P1] = '0;
  assign xp_rx[1][2][CHI_XP_EAST] = '0;
  assign xp_rx[1][2][CHI_XP_NORTH] = '0;
  assign xp_rx[1][2][CHI_XP_P1] = '0;

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // Device ports
  ////////////////////////////////////////////////////////////////////////////////////////////////

  assign xp_rx[0][0][CHI_XP_P0] = rnf0_rx_i;
  assign rnf0_tx_o = xp_tx[0][0][CHI_XP_P0];
  assign xp_rx[0][0][CHI_XP_P1] = rnf1_rx_i;
  assign rnf1_tx_o = xp_tx[0][0][CHI_XP_P1];
  assign xp_rx[0][2][CHI_XP_P0] = hnf0_rx_i;
  assign hnf0_tx_o = xp_tx[0][2][CHI_XP_P0];
  assign xp_rx[1][0][CHI_XP_P0] = snf0_rx_i;
  assign snf0_tx_o = xp_tx[1][0][CHI_XP_P0];
  assign xp_rx[1][2][CHI_XP_P0] = hnf1_rx_i;
  assign hnf1_tx_o = xp_tx[1][2][CHI_XP_P0];

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // Crosspoints
  ////////////////////////////////////////////////////////////////////////////////////////////////

  chi_xp #(
    .XIndex     (0),
    .YIndex     (0),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b110101)
  ) i_xp_0_0 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[0][0]),
    .tx_o (xp_tx[0][0])
  );

  chi_xp #(
    .XIndex     (1),
    .YIndex     (0),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b000111)
  ) i_xp_1_0 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[0][1]),
    .tx_o (xp_tx[0][1])
  );

  chi_xp #(
    .XIndex     (2),
    .YIndex     (0),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b010110)
  ) i_xp_2_0 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[0][2]),
    .tx_o (xp_tx[0][2])
  );

  chi_xp #(
    .XIndex     (0),
    .YIndex     (1),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011001)
  ) i_xp_0_1 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[1][0]),
    .tx_o (xp_tx[1][0])
  );

  chi_xp #(
    .XIndex     (1),
    .YIndex     (1),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b001011)
  ) i_xp_1_1 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[1][1]),
    .tx_o (xp_tx[1][1])
  );

  chi_xp #(
    .XIndex     (2),
    .YIndex     (1),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011010)
  ) i_xp_2_1 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[1][2]),
    .tx_o (xp_tx[1][2])
  );

endmodule
