// Generated by //hardware/ip/chi_noc/nocgen from mesh2x2.yml. Do not edit.
//
// Four crosspoints, one home node, one slave node
//
// A 2x2 mesh of crosspoints. Each carries CHI's four channel
// classes as four independent switches sharing nothing, which is what makes the
// protocol deadlock-free here; see //hardware/ip/chi_noc/README.md.
//
// A port is one `chi_xp_port_t` each way -- the four channels' flits, plus the
// L-Credits for the four it receives -- so wiring a neighbour is one assignment
// rather than thirty.
module mesh2x2_noc
  import chi_noc_flit_pkg::chi_xp_port_t;
  import chi_noc_pkg::CHI_XP_EAST;
  import chi_noc_pkg::CHI_XP_WEST;
  import chi_noc_pkg::CHI_XP_NORTH;
  import chi_noc_pkg::CHI_XP_SOUTH;
  import chi_noc_pkg::CHI_XP_P0;
  import chi_noc_pkg::CHI_XP_P1;
(
  input  logic clk_i,
  input  logic rst_ni,

  // One entry per device, indexed by the `<NAME>_INDEX` localparams in
  // mesh2x2_noc_pkg. An array rather than a port per device, because
  // a testbench has to be able to drive all of them the same way and a name
  // cannot be indexed; the localparams keep integration explicit, so a wire goes
  // to `dev_rx_i[mesh2x2_noc_pkg::RNF0_INDEX]`
  // and not to `dev_rx_i[3]`.
  //
  //   rnf0   RN-F  at (0, 0) P0, NodeID 11'h000
  //   rnf1   RN-F  at (0, 0) P1, NodeID 11'h001
  //   hnf0   HN-F  at (1, 0) P0, NodeID 11'h080
  //   hni0   HN-I  at (0, 1) P0, NodeID 11'h008
  //   snf0   SN-F  at (1, 1) P0, NodeID 11'h088
  input  chi_xp_port_t [4:0] dev_rx_i,
  output chi_xp_port_t [4:0] dev_tx_o
);

  // Indexed [y][x][direction]. `rx` is what a crosspoint is given, `tx` what it
  // drives, so a link is one assignment of the second to the first.
  chi_xp_port_t [1:0][1:0][5:0] xp_rx;
  chi_xp_port_t [1:0][1:0][5:0] xp_tx;

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // Links
  ////////////////////////////////////////////////////////////////////////////////////////////////

  assign xp_rx[0][0][CHI_XP_EAST] = xp_tx[0][1][CHI_XP_WEST];
  assign xp_rx[0][0][CHI_XP_NORTH] = xp_tx[1][0][CHI_XP_SOUTH];
  assign xp_rx[0][1][CHI_XP_WEST] = xp_tx[0][0][CHI_XP_EAST];
  assign xp_rx[0][1][CHI_XP_NORTH] = xp_tx[1][1][CHI_XP_SOUTH];
  assign xp_rx[1][0][CHI_XP_EAST] = xp_tx[1][1][CHI_XP_WEST];
  assign xp_rx[1][0][CHI_XP_SOUTH] = xp_tx[0][0][CHI_XP_NORTH];
  assign xp_rx[1][1][CHI_XP_WEST] = xp_tx[1][0][CHI_XP_EAST];
  assign xp_rx[1][1][CHI_XP_SOUTH] = xp_tx[0][1][CHI_XP_NORTH];

  // Ports that go nowhere. PortEnable removes their logic, so nothing reads
  // these; driving them keeps the elaborated netlist free of undriven nets
  // without adding any.
  assign xp_rx[0][0][CHI_XP_WEST] = '0;
  assign xp_rx[0][0][CHI_XP_SOUTH] = '0;
  assign xp_rx[0][1][CHI_XP_EAST] = '0;
  assign xp_rx[0][1][CHI_XP_SOUTH] = '0;
  assign xp_rx[0][1][CHI_XP_P1] = '0;
  assign xp_rx[1][0][CHI_XP_WEST] = '0;
  assign xp_rx[1][0][CHI_XP_NORTH] = '0;
  assign xp_rx[1][0][CHI_XP_P1] = '0;
  assign xp_rx[1][1][CHI_XP_EAST] = '0;
  assign xp_rx[1][1][CHI_XP_NORTH] = '0;
  assign xp_rx[1][1][CHI_XP_P1] = '0;

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // Device ports
  ////////////////////////////////////////////////////////////////////////////////////////////////

  // rnf0
  assign xp_rx[0][0][CHI_XP_P0] = dev_rx_i[0];
  assign dev_tx_o[0] = xp_tx[0][0][CHI_XP_P0];
  // rnf1
  assign xp_rx[0][0][CHI_XP_P1] = dev_rx_i[1];
  assign dev_tx_o[1] = xp_tx[0][0][CHI_XP_P1];
  // hnf0
  assign xp_rx[0][1][CHI_XP_P0] = dev_rx_i[2];
  assign dev_tx_o[2] = xp_tx[0][1][CHI_XP_P0];
  // hni0
  assign xp_rx[1][0][CHI_XP_P0] = dev_rx_i[3];
  assign dev_tx_o[3] = xp_tx[1][0][CHI_XP_P0];
  // snf0
  assign xp_rx[1][1][CHI_XP_P0] = dev_rx_i[4];
  assign dev_tx_o[4] = xp_tx[1][1][CHI_XP_P0];

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // Crosspoints
  ////////////////////////////////////////////////////////////////////////////////////////////////

  chi_xp #(
    .XIndex     (0),
    .YIndex     (0),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b110101)
  ) i_xp_0_0 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[0][0]),
    .tx_o (xp_tx[0][0])
  );

  chi_xp #(
    .XIndex     (1),
    .YIndex     (0),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b010110)
  ) i_xp_1_0 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[0][1]),
    .tx_o (xp_tx[0][1])
  );

  chi_xp #(
    .XIndex     (0),
    .YIndex     (1),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011001)
  ) i_xp_0_1 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[1][0]),
    .tx_o (xp_tx[1][0])
  );

  chi_xp #(
    .XIndex     (1),
    .YIndex     (1),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011010)
  ) i_xp_1_1 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[1][1]),
    .tx_o (xp_tx[1][1])
  );

endmodule
