// Generated by //hardware/ip/chi_noc/nocgen from mesh2x2.yml. Do not edit.
//
// Four crosspoints, one home node, one slave node
//
// Everything a design or a testbench needs to know about this network that is
// not in the netlist: which NodeID each device answers to, and which home node
// owns an address. //hardware/ip/chi_noc/nocgen also writes the same facts as
// JSON, so the scoreboard and this package cannot disagree.
package mesh2x2_noc_pkg;

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // Shape
  ////////////////////////////////////////////////////////////////////////////////////////////////

  localparam int unsigned SizeX = 2;
  localparam int unsigned SizeY = 2;
  localparam int unsigned DevicePorts = 2;
  localparam int unsigned LineBytes = 64;

  // NodeID is X above Y above the port index; see //hardware/ip/chi_noc/README.md.
  localparam int unsigned NodeIdXWidth = 4;
  localparam int unsigned NodeIdYWidth = 4;
  localparam int unsigned NodeIdPortWidth = 3;
  localparam int unsigned NodeIdWidth = 11;

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // Devices
  //
  // One localparam per device, named after it, so that RTL wiring a port says
  // which node it means rather than repeating a number.
  ////////////////////////////////////////////////////////////////////////////////////////////////

  localparam int unsigned NumDevices = 5;

  // RN-F at (0, 0) P0
  localparam int unsigned RNF0_INDEX = 0;
  localparam logic [NodeIdWidth-1:0] RNF0_NODE_ID = 11'h000;
  // RN-F at (0, 0) P1
  localparam int unsigned RNF1_INDEX = 1;
  localparam logic [NodeIdWidth-1:0] RNF1_NODE_ID = 11'h001;
  // HN-F at (1, 0) P0
  localparam int unsigned HNF0_INDEX = 2;
  localparam logic [NodeIdWidth-1:0] HNF0_NODE_ID = 11'h080;
  // HN-I at (0, 1) P0
  localparam int unsigned HNI0_INDEX = 3;
  localparam logic [NodeIdWidth-1:0] HNI0_NODE_ID = 11'h008;
  // SN-F at (1, 1) P0
  localparam int unsigned SNF0_INDEX = 4;
  localparam logic [NodeIdWidth-1:0] SNF0_NODE_ID = 11'h088;

  // Every device's NodeID, in index order, so a testbench can pick a target
  // without knowing any of their names.
  localparam logic [NodeIdWidth-1:0] DeviceNodeId [NumDevices] = '{
      11'h000,  // rnf0
      11'h001,  // rnf1
      11'h080,  // hnf0
      11'h008,  // hni0
      11'h088  // snf0
  };

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // What this topology should manage
  //
  // Computed by nocgen from the topology itself rather than quoted from a
  // textbook that assumed a different one, and asserted by
  // //hardware/ip/chi_noc/test. A document that drifts from the design is worse
  // than no document, so these are the document.
  ////////////////////////////////////////////////////////////////////////////////////////////////

  // Zero-load latency is `LatencyPerHop * hops + LatencyOverhead` cycles.
  localparam int unsigned LatencyPerHop = 2;
  localparam int unsigned LatencyOverhead = 4;

  // Flits per cycle per device, per channel class, in parts per thousand.
  // Integer because SystemVerilog localparams are, and a ratio of counted flits
  // to counted cycles is what a testbench can actually measure.
  localparam int unsigned SaturationBoundPerMille = 1000;
  localparam int unsigned MeanHopsPerMille = 960;

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // System Address Map
  //
  // Which home node owns a line. Every request node must answer this the same
  // way, which is why the table is generated once and included everywhere
  // rather than written per node.
  ////////////////////////////////////////////////////////////////////////////////////////////////

  localparam int unsigned AddrWidth = 48;
  localparam int unsigned NumRegions = 1;
  // The widest interleave in this map. A region with fewer pads with zeroes,
  // and RegionWays says how many of the entries mean anything.
  localparam int unsigned MaxInterleave = 1;

  localparam logic [AddrWidth-1:0] RegionBase [NumRegions] = '{
      48'h000080000000  // dram
  };

  localparam logic [AddrWidth-1:0] RegionLimit [NumRegions] = '{
      48'h0000c0000000
  };

  // Consecutive lines go to consecutive home nodes, and the count is a power of
  // two so the select is a bit slice rather than a divider.
  localparam int unsigned RegionWays [NumRegions] = '{
      1
  };

  localparam logic [NodeIdWidth-1:0] RegionTarget [NumRegions][MaxInterleave] = '{
      '{ 11'h080 }
  };

endpackage
