// Generated by //hardware/ip/chi_noc/nocgen from mesh4x4.yml. Do not edit.
//
// 16 crosspoints, one device each, four home nodes interleaved
//
// A 4x4 mesh of crosspoints. Each carries CHI's four channel
// classes as four independent switches sharing nothing, which is what makes the
// protocol deadlock-free here; see //hardware/ip/chi_noc/README.md.
//
// A port is one `chi_xp_port_t` each way -- the four channels' flits, plus the
// L-Credits for the four it receives -- so wiring a neighbour is one assignment
// rather than thirty.
module mesh4x4_noc
  import chi_noc_flit_pkg::chi_xp_port_t;
  import chi_noc_pkg::CHI_XP_EAST;
  import chi_noc_pkg::CHI_XP_WEST;
  import chi_noc_pkg::CHI_XP_NORTH;
  import chi_noc_pkg::CHI_XP_SOUTH;
  import chi_noc_pkg::CHI_XP_P0;
  import chi_noc_pkg::CHI_XP_P1;
(
  input  logic clk_i,
  input  logic rst_ni,

  // rnf0: RN-F at (0, 0) P0, NodeID 11'h000
  input  chi_xp_port_t rnf0_rx_i,
  output chi_xp_port_t rnf0_tx_o,
  // rnf1: RN-F at (1, 0) P0, NodeID 11'h080
  input  chi_xp_port_t rnf1_rx_i,
  output chi_xp_port_t rnf1_tx_o,
  // rnf2: RN-F at (2, 0) P0, NodeID 11'h100
  input  chi_xp_port_t rnf2_rx_i,
  output chi_xp_port_t rnf2_tx_o,
  // rnf3: RN-F at (3, 0) P0, NodeID 11'h180
  input  chi_xp_port_t rnf3_rx_i,
  output chi_xp_port_t rnf3_tx_o,
  // hnf0: HN-F at (0, 1) P0, NodeID 11'h008
  input  chi_xp_port_t hnf0_rx_i,
  output chi_xp_port_t hnf0_tx_o,
  // hnf1: HN-F at (1, 1) P0, NodeID 11'h088
  input  chi_xp_port_t hnf1_rx_i,
  output chi_xp_port_t hnf1_tx_o,
  // hnf2: HN-F at (2, 1) P0, NodeID 11'h108
  input  chi_xp_port_t hnf2_rx_i,
  output chi_xp_port_t hnf2_tx_o,
  // hnf3: HN-F at (3, 1) P0, NodeID 11'h188
  input  chi_xp_port_t hnf3_rx_i,
  output chi_xp_port_t hnf3_tx_o,
  // snf0: SN-F at (0, 2) P0, NodeID 11'h010
  input  chi_xp_port_t snf0_rx_i,
  output chi_xp_port_t snf0_tx_o,
  // rni0: RN-I at (1, 2) P0, NodeID 11'h090
  input  chi_xp_port_t rni0_rx_i,
  output chi_xp_port_t rni0_tx_o,
  // hni0: HN-I at (2, 2) P0, NodeID 11'h110
  input  chi_xp_port_t hni0_rx_i,
  output chi_xp_port_t hni0_tx_o,
  // snf1: SN-F at (3, 2) P0, NodeID 11'h190
  input  chi_xp_port_t snf1_rx_i,
  output chi_xp_port_t snf1_tx_o,
  // rnf4: RN-F at (0, 3) P0, NodeID 11'h018
  input  chi_xp_port_t rnf4_rx_i,
  output chi_xp_port_t rnf4_tx_o,
  // rnf5: RN-F at (1, 3) P0, NodeID 11'h098
  input  chi_xp_port_t rnf5_rx_i,
  output chi_xp_port_t rnf5_tx_o,
  // rnf6: RN-F at (2, 3) P0, NodeID 11'h118
  input  chi_xp_port_t rnf6_rx_i,
  output chi_xp_port_t rnf6_tx_o,
  // rnf7: RN-F at (3, 3) P0, NodeID 11'h198
  input  chi_xp_port_t rnf7_rx_i,
  output chi_xp_port_t rnf7_tx_o
);

  // Indexed [y][x][direction]. `rx` is what a crosspoint is given, `tx` what it
  // drives, so a link is one assignment of the second to the first.
  chi_xp_port_t [3:0][3:0][5:0] xp_rx;
  chi_xp_port_t [3:0][3:0][5:0] xp_tx;

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // Links
  ////////////////////////////////////////////////////////////////////////////////////////////////

  assign xp_rx[0][0][CHI_XP_EAST] = xp_tx[0][1][CHI_XP_WEST];
  assign xp_rx[0][0][CHI_XP_NORTH] = xp_tx[1][0][CHI_XP_SOUTH];
  assign xp_rx[0][1][CHI_XP_EAST] = xp_tx[0][2][CHI_XP_WEST];
  assign xp_rx[0][1][CHI_XP_WEST] = xp_tx[0][0][CHI_XP_EAST];
  assign xp_rx[0][1][CHI_XP_NORTH] = xp_tx[1][1][CHI_XP_SOUTH];
  assign xp_rx[0][2][CHI_XP_EAST] = xp_tx[0][3][CHI_XP_WEST];
  assign xp_rx[0][2][CHI_XP_WEST] = xp_tx[0][1][CHI_XP_EAST];
  assign xp_rx[0][2][CHI_XP_NORTH] = xp_tx[1][2][CHI_XP_SOUTH];
  assign xp_rx[0][3][CHI_XP_WEST] = xp_tx[0][2][CHI_XP_EAST];
  assign xp_rx[0][3][CHI_XP_NORTH] = xp_tx[1][3][CHI_XP_SOUTH];
  assign xp_rx[1][0][CHI_XP_EAST] = xp_tx[1][1][CHI_XP_WEST];
  assign xp_rx[1][0][CHI_XP_NORTH] = xp_tx[2][0][CHI_XP_SOUTH];
  assign xp_rx[1][0][CHI_XP_SOUTH] = xp_tx[0][0][CHI_XP_NORTH];
  assign xp_rx[1][1][CHI_XP_EAST] = xp_tx[1][2][CHI_XP_WEST];
  assign xp_rx[1][1][CHI_XP_WEST] = xp_tx[1][0][CHI_XP_EAST];
  assign xp_rx[1][1][CHI_XP_NORTH] = xp_tx[2][1][CHI_XP_SOUTH];
  assign xp_rx[1][1][CHI_XP_SOUTH] = xp_tx[0][1][CHI_XP_NORTH];
  assign xp_rx[1][2][CHI_XP_EAST] = xp_tx[1][3][CHI_XP_WEST];
  assign xp_rx[1][2][CHI_XP_WEST] = xp_tx[1][1][CHI_XP_EAST];
  assign xp_rx[1][2][CHI_XP_NORTH] = xp_tx[2][2][CHI_XP_SOUTH];
  assign xp_rx[1][2][CHI_XP_SOUTH] = xp_tx[0][2][CHI_XP_NORTH];
  assign xp_rx[1][3][CHI_XP_WEST] = xp_tx[1][2][CHI_XP_EAST];
  assign xp_rx[1][3][CHI_XP_NORTH] = xp_tx[2][3][CHI_XP_SOUTH];
  assign xp_rx[1][3][CHI_XP_SOUTH] = xp_tx[0][3][CHI_XP_NORTH];
  assign xp_rx[2][0][CHI_XP_EAST] = xp_tx[2][1][CHI_XP_WEST];
  assign xp_rx[2][0][CHI_XP_NORTH] = xp_tx[3][0][CHI_XP_SOUTH];
  assign xp_rx[2][0][CHI_XP_SOUTH] = xp_tx[1][0][CHI_XP_NORTH];
  assign xp_rx[2][1][CHI_XP_EAST] = xp_tx[2][2][CHI_XP_WEST];
  assign xp_rx[2][1][CHI_XP_WEST] = xp_tx[2][0][CHI_XP_EAST];
  assign xp_rx[2][1][CHI_XP_NORTH] = xp_tx[3][1][CHI_XP_SOUTH];
  assign xp_rx[2][1][CHI_XP_SOUTH] = xp_tx[1][1][CHI_XP_NORTH];
  assign xp_rx[2][2][CHI_XP_EAST] = xp_tx[2][3][CHI_XP_WEST];
  assign xp_rx[2][2][CHI_XP_WEST] = xp_tx[2][1][CHI_XP_EAST];
  assign xp_rx[2][2][CHI_XP_NORTH] = xp_tx[3][2][CHI_XP_SOUTH];
  assign xp_rx[2][2][CHI_XP_SOUTH] = xp_tx[1][2][CHI_XP_NORTH];
  assign xp_rx[2][3][CHI_XP_WEST] = xp_tx[2][2][CHI_XP_EAST];
  assign xp_rx[2][3][CHI_XP_NORTH] = xp_tx[3][3][CHI_XP_SOUTH];
  assign xp_rx[2][3][CHI_XP_SOUTH] = xp_tx[1][3][CHI_XP_NORTH];
  assign xp_rx[3][0][CHI_XP_EAST] = xp_tx[3][1][CHI_XP_WEST];
  assign xp_rx[3][0][CHI_XP_SOUTH] = xp_tx[2][0][CHI_XP_NORTH];
  assign xp_rx[3][1][CHI_XP_EAST] = xp_tx[3][2][CHI_XP_WEST];
  assign xp_rx[3][1][CHI_XP_WEST] = xp_tx[3][0][CHI_XP_EAST];
  assign xp_rx[3][1][CHI_XP_SOUTH] = xp_tx[2][1][CHI_XP_NORTH];
  assign xp_rx[3][2][CHI_XP_EAST] = xp_tx[3][3][CHI_XP_WEST];
  assign xp_rx[3][2][CHI_XP_WEST] = xp_tx[3][1][CHI_XP_EAST];
  assign xp_rx[3][2][CHI_XP_SOUTH] = xp_tx[2][2][CHI_XP_NORTH];
  assign xp_rx[3][3][CHI_XP_WEST] = xp_tx[3][2][CHI_XP_EAST];
  assign xp_rx[3][3][CHI_XP_SOUTH] = xp_tx[2][3][CHI_XP_NORTH];

  // Ports that go nowhere. PortEnable removes their logic, so nothing reads
  // these; driving them keeps the elaborated netlist free of undriven nets
  // without adding any.
  assign xp_rx[0][0][CHI_XP_WEST] = '0;
  assign xp_rx[0][0][CHI_XP_SOUTH] = '0;
  assign xp_rx[0][0][CHI_XP_P1] = '0;
  assign xp_rx[0][1][CHI_XP_SOUTH] = '0;
  assign xp_rx[0][1][CHI_XP_P1] = '0;
  assign xp_rx[0][2][CHI_XP_SOUTH] = '0;
  assign xp_rx[0][2][CHI_XP_P1] = '0;
  assign xp_rx[0][3][CHI_XP_EAST] = '0;
  assign xp_rx[0][3][CHI_XP_SOUTH] = '0;
  assign xp_rx[0][3][CHI_XP_P1] = '0;
  assign xp_rx[1][0][CHI_XP_WEST] = '0;
  assign xp_rx[1][0][CHI_XP_P1] = '0;
  assign xp_rx[1][1][CHI_XP_P1] = '0;
  assign xp_rx[1][2][CHI_XP_P1] = '0;
  assign xp_rx[1][3][CHI_XP_EAST] = '0;
  assign xp_rx[1][3][CHI_XP_P1] = '0;
  assign xp_rx[2][0][CHI_XP_WEST] = '0;
  assign xp_rx[2][0][CHI_XP_P1] = '0;
  assign xp_rx[2][1][CHI_XP_P1] = '0;
  assign xp_rx[2][2][CHI_XP_P1] = '0;
  assign xp_rx[2][3][CHI_XP_EAST] = '0;
  assign xp_rx[2][3][CHI_XP_P1] = '0;
  assign xp_rx[3][0][CHI_XP_WEST] = '0;
  assign xp_rx[3][0][CHI_XP_NORTH] = '0;
  assign xp_rx[3][0][CHI_XP_P1] = '0;
  assign xp_rx[3][1][CHI_XP_NORTH] = '0;
  assign xp_rx[3][1][CHI_XP_P1] = '0;
  assign xp_rx[3][2][CHI_XP_NORTH] = '0;
  assign xp_rx[3][2][CHI_XP_P1] = '0;
  assign xp_rx[3][3][CHI_XP_EAST] = '0;
  assign xp_rx[3][3][CHI_XP_NORTH] = '0;
  assign xp_rx[3][3][CHI_XP_P1] = '0;

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // Device ports
  ////////////////////////////////////////////////////////////////////////////////////////////////

  assign xp_rx[0][0][CHI_XP_P0] = rnf0_rx_i;
  assign rnf0_tx_o = xp_tx[0][0][CHI_XP_P0];
  assign xp_rx[0][1][CHI_XP_P0] = rnf1_rx_i;
  assign rnf1_tx_o = xp_tx[0][1][CHI_XP_P0];
  assign xp_rx[0][2][CHI_XP_P0] = rnf2_rx_i;
  assign rnf2_tx_o = xp_tx[0][2][CHI_XP_P0];
  assign xp_rx[0][3][CHI_XP_P0] = rnf3_rx_i;
  assign rnf3_tx_o = xp_tx[0][3][CHI_XP_P0];
  assign xp_rx[1][0][CHI_XP_P0] = hnf0_rx_i;
  assign hnf0_tx_o = xp_tx[1][0][CHI_XP_P0];
  assign xp_rx[1][1][CHI_XP_P0] = hnf1_rx_i;
  assign hnf1_tx_o = xp_tx[1][1][CHI_XP_P0];
  assign xp_rx[1][2][CHI_XP_P0] = hnf2_rx_i;
  assign hnf2_tx_o = xp_tx[1][2][CHI_XP_P0];
  assign xp_rx[1][3][CHI_XP_P0] = hnf3_rx_i;
  assign hnf3_tx_o = xp_tx[1][3][CHI_XP_P0];
  assign xp_rx[2][0][CHI_XP_P0] = snf0_rx_i;
  assign snf0_tx_o = xp_tx[2][0][CHI_XP_P0];
  assign xp_rx[2][1][CHI_XP_P0] = rni0_rx_i;
  assign rni0_tx_o = xp_tx[2][1][CHI_XP_P0];
  assign xp_rx[2][2][CHI_XP_P0] = hni0_rx_i;
  assign hni0_tx_o = xp_tx[2][2][CHI_XP_P0];
  assign xp_rx[2][3][CHI_XP_P0] = snf1_rx_i;
  assign snf1_tx_o = xp_tx[2][3][CHI_XP_P0];
  assign xp_rx[3][0][CHI_XP_P0] = rnf4_rx_i;
  assign rnf4_tx_o = xp_tx[3][0][CHI_XP_P0];
  assign xp_rx[3][1][CHI_XP_P0] = rnf5_rx_i;
  assign rnf5_tx_o = xp_tx[3][1][CHI_XP_P0];
  assign xp_rx[3][2][CHI_XP_P0] = rnf6_rx_i;
  assign rnf6_tx_o = xp_tx[3][2][CHI_XP_P0];
  assign xp_rx[3][3][CHI_XP_P0] = rnf7_rx_i;
  assign rnf7_tx_o = xp_tx[3][3][CHI_XP_P0];

  ////////////////////////////////////////////////////////////////////////////////////////////////
  // Crosspoints
  ////////////////////////////////////////////////////////////////////////////////////////////////

  chi_xp #(
    .XIndex     (0),
    .YIndex     (0),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b010101)
  ) i_xp_0_0 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[0][0]),
    .tx_o (xp_tx[0][0])
  );

  chi_xp #(
    .XIndex     (1),
    .YIndex     (0),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b010111)
  ) i_xp_1_0 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[0][1]),
    .tx_o (xp_tx[0][1])
  );

  chi_xp #(
    .XIndex     (2),
    .YIndex     (0),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b010111)
  ) i_xp_2_0 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[0][2]),
    .tx_o (xp_tx[0][2])
  );

  chi_xp #(
    .XIndex     (3),
    .YIndex     (0),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b010110)
  ) i_xp_3_0 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[0][3]),
    .tx_o (xp_tx[0][3])
  );

  chi_xp #(
    .XIndex     (0),
    .YIndex     (1),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011101)
  ) i_xp_0_1 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[1][0]),
    .tx_o (xp_tx[1][0])
  );

  chi_xp #(
    .XIndex     (1),
    .YIndex     (1),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011111)
  ) i_xp_1_1 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[1][1]),
    .tx_o (xp_tx[1][1])
  );

  chi_xp #(
    .XIndex     (2),
    .YIndex     (1),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011111)
  ) i_xp_2_1 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[1][2]),
    .tx_o (xp_tx[1][2])
  );

  chi_xp #(
    .XIndex     (3),
    .YIndex     (1),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011110)
  ) i_xp_3_1 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[1][3]),
    .tx_o (xp_tx[1][3])
  );

  chi_xp #(
    .XIndex     (0),
    .YIndex     (2),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011101)
  ) i_xp_0_2 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[2][0]),
    .tx_o (xp_tx[2][0])
  );

  chi_xp #(
    .XIndex     (1),
    .YIndex     (2),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011111)
  ) i_xp_1_2 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[2][1]),
    .tx_o (xp_tx[2][1])
  );

  chi_xp #(
    .XIndex     (2),
    .YIndex     (2),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011111)
  ) i_xp_2_2 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[2][2]),
    .tx_o (xp_tx[2][2])
  );

  chi_xp #(
    .XIndex     (3),
    .YIndex     (2),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011110)
  ) i_xp_3_2 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[2][3]),
    .tx_o (xp_tx[2][3])
  );

  chi_xp #(
    .XIndex     (0),
    .YIndex     (3),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011001)
  ) i_xp_0_3 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[3][0]),
    .tx_o (xp_tx[3][0])
  );

  chi_xp #(
    .XIndex     (1),
    .YIndex     (3),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011011)
  ) i_xp_1_3 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[3][1]),
    .tx_o (xp_tx[3][1])
  );

  chi_xp #(
    .XIndex     (2),
    .YIndex     (3),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011011)
  ) i_xp_2_3 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[3][2]),
    .tx_o (xp_tx[3][2])
  );

  chi_xp #(
    .XIndex     (3),
    .YIndex     (3),
    // P1, P0, South, North, West, East -- MSB first.
    .PortEnable (6'b011010)
  ) i_xp_3_3 (
    .clk_i,
    .rst_ni,
    .rx_i (xp_rx[3][3]),
    .tx_o (xp_tx[3][3])
  );

endmodule
