apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: buildbarn
resources:
  - namespace.yaml
  - storage.yaml
  - frontend-rw.yaml
  - frontend-ro.yaml
  - scheduler.yaml
  - worker.yaml
configMapGenerator:
  - name: buildbarn-config
    files:
      - config/common.libsonnet
      - config/frontend.libsonnet
      - config/frontend-ro.jsonnet
      - config/frontend-rw.jsonnet
      - config/storage.jsonnet
      - config/scheduler.jsonnet
      - config/worker.jsonnet
      - config/runner.jsonnet
generatorOptions:
  disableNameSuffixHash: true
