apiVersion: v1
kind: Service
metadata:
  name: scheduler
  namespace: buildbarn
spec:
  selector:
    app: scheduler
  ports:
    - {name: client, port: 8982, targetPort: 8982}
    - {name: worker, port: 8983, targetPort: 8983}
    - {name: state, port: 8984, targetPort: 8984}
    - {name: metrics, port: 9980, targetPort: 9980}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: buildbarn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      containers:
        - name: scheduler
          image: ghcr.io/buildbarn/bb-scheduler@sha256:096d2d3a2e4d4134e37bda3147e1d2385be6c1b05eba4b6565ee469fc8dc9394
          args: [/config/scheduler.jsonnet]
          ports:
            - {containerPort: 8982}
            - {containerPort: 8983}
            - {containerPort: 8984}
            - {containerPort: 9980}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {cpu: 50m, memory: 128Mi}
            limits: {memory: 512Mi}
          volumeMounts:
            - {name: config, mountPath: /config}
      volumes:
        - name: config
          configMap:
            name: buildbarn-config
