apiVersion: v1
data:
    network: ENC[AES256_GCM,data:TxJAU1ODJIFLkmbj,iv:dAfc7/W0GiB/4V/FFh/sqW5hOw7D16or+R2opiE9404=,tag:3+PO6jqqSrlwTt1FOd2kIg==,type:str]
    token: ENC[AES256_GCM,data:qfEQZMIp4FkMSBEk0WeVFgDClLT26A8W5Ucam6jnXXRZZLz3wdOdD2Py3jlT7syXGO5DjWo5e4YWdSRDKImI1e8GxfSAdg3QLRwaYj354DTHk1JamAJcqw==,iv:sLtQEdj6xm1jgQrK+BDPstrJ4z5rXeBdlknIemwSZ+s=,tag:DM7Rbbvv+a32SnHoMZmqbQ==,type:str]
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQzE4RGNYYXIwWlM5TjNz
            SXlFNEtqWk9kVHltRi9XT1JNemhQRHRSRzFZCkV0R0tYN0dZaHc1QzlYRmdQalhR
            UjlvU1dhMzJSeUpSeUpzOUV6dWhWeU0KLS0tIFhKRDAreVFzZnpUS2xLd2FoK2FO
            Z0dHQS9pUHNFNnF5ZDlSWnFRSUhHRW8KwD6KAVQIQKi28udYkITOM9NSHMUzfnl5
            0WGXqVBwfubTHjR/YG6eDnES/kowLNHbTETeN/J4kYTKJFqJJn8k+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n8ujfcvu9c02jksjd8xfn8fcadqsjww5m42jcyknwekxj6h33e9s9x2cxj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T07:07:45Z"
    mac: ENC[AES256_GCM,data:cPC5HB2iR2Pt6KC/iBVLHB3P+qKjWxGJptIbtp9iMSVev9ODwQQXvlp2xDTRhSK04PAIXd255ACNIOeR9GUdURADj+JHZrVxpt11+YZg8gwWHj5FF9Zrp0hht7p708bMzye+V9jV4/4P6vOpXwcpQe4MVTngcla+ftlyBo5d/VI=,iv:rT41nZFZhitiBmgPOEr8OEWYzhgDextNs0zLU2jAo+8=,tag:duQPpdjJzaaJNHVxMV4IgQ==,type:str]
    version: 3.13.3
