apiVersion: v1
data:
    password: ENC[AES256_GCM,data:b2alpgcLmuPFe+hXCvRguZf1wig5tvVdPryafLJcGVOuDpWjupd+bY1MKU1b/dX0JDETA4Q40es=,iv:tVKl28SGP44Y0HxwhZOf4RJ5YWhEe9U5W+VRsiBQgH8=,tag:p60WyAvjnDs/XzbFUM0XTQ==,type:str]
kind: Secret
metadata:
    name: postgres
    namespace: bb-portal
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1V2hiYUVoUnJ2ZFFQbXdH
            REgydjV0dkFTOWIxQ2ZjUndhQmJRQ09hYWtFCldzNzRhRnpKMFBkYWZFSTc2WnlP
            N2hkV3JnQmMvdjJudmI3TDEwWDE4WEkKLS0tIFo1MjBCTkFZV05uUmNFU1ZYNzF6
            M0FyVURHa3hLOVdzL2ViTVJuYURST3cKAZ2p6GJCnbGNdjEhxhzWzEpQ8EKLwOBr
            XKQ3gIiZa1M8aRRofELBWl0OvFXscLCQy6pSlsX6c43o8SZNSOZtKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n8ujfcvu9c02jksjd8xfn8fcadqsjww5m42jcyknwekxj6h33e9s9x2cxj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T10:49:17Z"
    mac: ENC[AES256_GCM,data:3b6NA8tal3xzF/5hFMCy8yyxe/aOHFGM+8FUFZVT9dCpvmC1ME4iLzbjJ23W+s/A6cgwdsBya+5P4Z6fSBHuGie1hgKAVQ4MLSA1VdW1zKuKw2TuNu24I2fMA34OaJzRbWMRcbwmnAz7LPnGz1i6hn7gZdPvsezMSGjlcwhUraE=,iv:9T9HeABojpTGCMi8W7+nAZAm6vByRUGGI/f1mULo26U=,tag:Mf8tvlSC1kIKQnjvfPuyzw==,type:str]
    version: 3.13.3
