load(":tofu.bzl", "tofu_command")

exports_files(["tofu_wrapper.sh"])

# bazel run //infra/tofu:fmt -- -check
# bazel run //infra/tofu:init
# bazel run //infra/tofu:plan
# bazel run //infra/tofu:apply
[
    tofu_command(
        name = subcommand,
        module = "infra/tofu",
    )
    for subcommand in [
        "apply",
        "fmt",
        "init",
        "plan",
        "validate",
    ]
]
