load("//tools:workspace_command.bzl", "workspace_command")

# bazel run //infra/tofu:fmt -- -check
# bazel run //infra/tofu:init
# bazel run //infra/tofu:plan
# bazel run //infra/tofu:apply
[
    workspace_command(
        name = subcommand,
        args = [subcommand],
        tool = "@multitool//tools/tofu",
        workdir = "infra/tofu",
    )
    for subcommand in [
        "apply",
        "fmt",
        "init",
        "plan",
        "validate",
    ]
]
